/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EstimationRouteImport } from './routes/estimation'
import { Route as DevenirArtisanRouteImport } from './routes/devenir-artisan'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CharteQualiteRouteImport } from './routes/charte-qualite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProOffresRouteImport } from './routes/pro.offres'
import { Route as ProFacturationRouteImport } from './routes/pro.facturation'
import { Route as DevenirArtisanInscriptionRouteImport } from './routes/devenir-artisan.inscription'
import { Route as DemoMicroReassuranceRouteImport } from './routes/demo.micro-reassurance'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMonetisationRouteImport } from './routes/admin.monetisation'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminArtisansRouteImport } from './routes/admin.artisans'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated/pro'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedDevisRouteImport } from './routes/_authenticated/devis'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimationRoute = EstimationRouteImport.update({
  id: '/estimation',
  path: '/estimation',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirArtisanRoute = DevenirArtisanRouteImport.update({
  id: '/devenir-artisan',
  path: '/devenir-artisan',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CharteQualiteRoute = CharteQualiteRouteImport.update({
  id: '/charte-qualite',
  path: '/charte-qualite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProOffresRoute = ProOffresRouteImport.update({
  id: '/pro/offres',
  path: '/pro/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProFacturationRoute = ProFacturationRouteImport.update({
  id: '/pro/facturation',
  path: '/pro/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirArtisanInscriptionRoute =
  DevenirArtisanInscriptionRouteImport.update({
    id: '/inscription',
    path: '/inscription',
    getParentRoute: () => DevenirArtisanRoute,
  } as any)
const DemoMicroReassuranceRoute = DemoMicroReassuranceRouteImport.update({
  id: '/demo/micro-reassurance',
  path: '/demo/micro-reassurance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonetisationRoute = AdminMonetisationRouteImport.update({
  id: '/monetisation',
  path: '/monetisation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtisansRoute = AdminArtisansRouteImport.update({
  id: '/artisans',
  path: '/artisans',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevisRoute = AuthenticatedDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/charte-qualite': typeof CharteQualiteRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/devenir-artisan': typeof DevenirArtisanRouteWithChildren
  '/estimation': typeof EstimationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/devis': typeof AuthenticatedDevisRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/pro': typeof AuthenticatedProRoute
  '/admin/artisans': typeof AdminArtisansRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/monetisation': typeof AdminMonetisationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/support': typeof AdminSupportRoute
  '/demo/micro-reassurance': typeof DemoMicroReassuranceRoute
  '/devenir-artisan/inscription': typeof DevenirArtisanInscriptionRoute
  '/pro/facturation': typeof ProFacturationRoute
  '/pro/offres': typeof ProOffresRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charte-qualite': typeof CharteQualiteRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/devenir-artisan': typeof DevenirArtisanRouteWithChildren
  '/estimation': typeof EstimationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/devis': typeof AuthenticatedDevisRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/pro': typeof AuthenticatedProRoute
  '/admin/artisans': typeof AdminArtisansRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/monetisation': typeof AdminMonetisationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/support': typeof AdminSupportRoute
  '/demo/micro-reassurance': typeof DemoMicroReassuranceRoute
  '/devenir-artisan/inscription': typeof DevenirArtisanInscriptionRoute
  '/pro/facturation': typeof ProFacturationRoute
  '/pro/offres': typeof ProOffresRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/charte-qualite': typeof CharteQualiteRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/devenir-artisan': typeof DevenirArtisanRouteWithChildren
  '/estimation': typeof EstimationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/devis': typeof AuthenticatedDevisRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/pro': typeof AuthenticatedProRoute
  '/admin/artisans': typeof AdminArtisansRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/monetisation': typeof AdminMonetisationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/support': typeof AdminSupportRoute
  '/demo/micro-reassurance': typeof DemoMicroReassuranceRoute
  '/devenir-artisan/inscription': typeof DevenirArtisanInscriptionRoute
  '/pro/facturation': typeof ProFacturationRoute
  '/pro/offres': typeof ProOffresRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/charte-qualite'
    | '/contact'
    | '/design-system'
    | '/devenir-artisan'
    | '/estimation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/devis'
    | '/historique'
    | '/pro'
    | '/admin/artisans'
    | '/admin/clients'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/monetisation'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/support'
    | '/demo/micro-reassurance'
    | '/devenir-artisan/inscription'
    | '/pro/facturation'
    | '/pro/offres'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charte-qualite'
    | '/contact'
    | '/design-system'
    | '/devenir-artisan'
    | '/estimation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/devis'
    | '/historique'
    | '/pro'
    | '/admin/artisans'
    | '/admin/clients'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/monetisation'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/support'
    | '/demo/micro-reassurance'
    | '/devenir-artisan/inscription'
    | '/pro/facturation'
    | '/pro/offres'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/charte-qualite'
    | '/contact'
    | '/design-system'
    | '/devenir-artisan'
    | '/estimation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_authenticated/devis'
    | '/_authenticated/historique'
    | '/_authenticated/pro'
    | '/admin/artisans'
    | '/admin/clients'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/monetisation'
    | '/admin/notifications'
    | '/admin/parametres'
    | '/admin/support'
    | '/demo/micro-reassurance'
    | '/devenir-artisan/inscription'
    | '/pro/facturation'
    | '/pro/offres'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CharteQualiteRoute: typeof CharteQualiteRoute
  ContactRoute: typeof ContactRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DevenirArtisanRoute: typeof DevenirArtisanRouteWithChildren
  EstimationRoute: typeof EstimationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DemoMicroReassuranceRoute: typeof DemoMicroReassuranceRoute
  ProFacturationRoute: typeof ProFacturationRoute
  ProOffresRoute: typeof ProOffresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimation': {
      id: '/estimation'
      path: '/estimation'
      fullPath: '/estimation'
      preLoaderRoute: typeof EstimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-artisan': {
      id: '/devenir-artisan'
      path: '/devenir-artisan'
      fullPath: '/devenir-artisan'
      preLoaderRoute: typeof DevenirArtisanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charte-qualite': {
      id: '/charte-qualite'
      path: '/charte-qualite'
      fullPath: '/charte-qualite'
      preLoaderRoute: typeof CharteQualiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pro/offres': {
      id: '/pro/offres'
      path: '/pro/offres'
      fullPath: '/pro/offres'
      preLoaderRoute: typeof ProOffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/facturation': {
      id: '/pro/facturation'
      path: '/pro/facturation'
      fullPath: '/pro/facturation'
      preLoaderRoute: typeof ProFacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-artisan/inscription': {
      id: '/devenir-artisan/inscription'
      path: '/inscription'
      fullPath: '/devenir-artisan/inscription'
      preLoaderRoute: typeof DevenirArtisanInscriptionRouteImport
      parentRoute: typeof DevenirArtisanRoute
    }
    '/demo/micro-reassurance': {
      id: '/demo/micro-reassurance'
      path: '/demo/micro-reassurance'
      fullPath: '/demo/micro-reassurance'
      preLoaderRoute: typeof DemoMicroReassuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monetisation': {
      id: '/admin/monetisation'
      path: '/monetisation'
      fullPath: '/admin/monetisation'
      preLoaderRoute: typeof AdminMonetisationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artisans': {
      id: '/admin/artisans'
      path: '/artisans'
      fullPath: '/admin/artisans'
      preLoaderRoute: typeof AdminArtisansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devis': {
      id: '/_authenticated/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof AuthenticatedDevisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDevisRoute: typeof AuthenticatedDevisRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedProRoute: typeof AuthenticatedProRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDevisRoute: AuthenticatedDevisRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedProRoute: AuthenticatedProRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminArtisansRoute: typeof AdminArtisansRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminMonetisationRoute: typeof AdminMonetisationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtisansRoute: AdminArtisansRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminMonetisationRoute: AdminMonetisationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DevenirArtisanRouteChildren {
  DevenirArtisanInscriptionRoute: typeof DevenirArtisanInscriptionRoute
}

const DevenirArtisanRouteChildren: DevenirArtisanRouteChildren = {
  DevenirArtisanInscriptionRoute: DevenirArtisanInscriptionRoute,
}

const DevenirArtisanRouteWithChildren = DevenirArtisanRoute._addFileChildren(
  DevenirArtisanRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CharteQualiteRoute: CharteQualiteRoute,
  ContactRoute: ContactRoute,
  DesignSystemRoute: DesignSystemRoute,
  DevenirArtisanRoute: DevenirArtisanRouteWithChildren,
  EstimationRoute: EstimationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DemoMicroReassuranceRoute: DemoMicroReassuranceRoute,
  ProFacturationRoute: ProFacturationRoute,
  ProOffresRoute: ProOffresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
